// Importing required functions from Redux Toolkit
import { createSlice, configureStore } from "@reduxjs/toolkit";

// Creating a slice of the Redux store for authentication
const authSlice = createSlice({
    name: "auth", // Name of the slice
    initialState: { user: "", isLoggedIn: false }, // Initial state for the slice
    reducers: {
        // Reducer to set user as logged in
        login(state) {
            state.isLoggedIn = true;
        },
        // Reducer to set user as logged out
        logout(state) {
            state.isLoggedIn = false;
        }
    },
});

// Exporting actions generated by createSlice (login, logout)
export const authActions = authSlice.actions;

// Creating and exporting the Redux store with our auth slice as the reducer
export const store = configureStore({
    reducer: authSlice.reducer, // You can add more slices here in the future
});
